#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "epicyon"
name = "Epicyon"
description.en = "Federated social network server"
description.fr = "Serveur de réseau social fédéré"

version = "2023.03.17~ynh2"

maintainers = []

[upstream]
license = "AGPL-1.0-or-later"
website = "https://epicyon.net"
code = "https://gitlab.com/bashrc2/epicyon/"
fund = "https://www.patreon.com/freedombone"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://gitlab.com/bashrc2/epicyon/-/archive/90a31c45ee2fc1c4c160f029c94be0911d14a8f5/epicyon-90a31c45ee2fc1c4c160f029c94be0911d14a8f5.tar.gz"
    sha256 = "7807065c6d68073e6f8b4370297b22c659d5ea9e4a8609dbfb2332d0eb4e990d"

    autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "python3-socks",
        "imagemagick",
        "python3-setuptools",
        "python3-cryptography",
        "python3-dateutil",
        "python3-idna",
        "python3-requests",
        "python3-flake8",
        "python3-django-timezone-field",
        "python3-pyqrcode",
        "python3-png",
        "python3-bandit",
        "libimage-exiftool-perl",
    ]
